### ISSUE TITLE
AntiXray is not working.

### ISSUE THREAD

**Issue by Mcayear** [wode490390/AntiXray#13]
AntiXray does not work properly in PowerNukkit 1.17.0

```
2021-06-20 08:15:59.935 [main] INFO  - 开启 AntiXray v1.2.3 中
2021-06-20 08:15:59.961 [main] FATAL - An error occurred while enabling the plugin AntiXray, 1.2.3, cn.wode490390.nukkit.antixray.AntiXray
java.lang.ExceptionInInitializerError: null
	at cn.wode490390.nukkit.antixray.AntiXray.onEnable(AntiXray.java:162) ~[?:?]
	at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:101) ~[powernukkit.jar:?]
	at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:120) ~[powernukkit.jar:?]
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:459) [powernukkit.jar:?]
	at cn.nukkit.Server.enablePlugin(Server.java:938) [powernukkit.jar:?]
	at cn.nukkit.Server.enablePlugins(Server.java:927) [powernukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:765) [powernukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:199) [powernukkit.jar:?]
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: storage
	at cn.wode490390.nukkit.antixray.WorldHandler.<clinit>(WorldHandler.java:79) ~[?:?]
	... 8 more
Caused by: java.lang.NoSuchFieldException: storage
	at java.lang.Class.getDeclaredField(Unknown Source) ~[?:1.8.0_281]
	at cn.wode490390.nukkit.antixray.WorldHandler.<clinit>(WorldHandler.java:75) ~[?:?]
	... 8 more
2021-06-20 08:16:00.008 [main] INFO  - 关闭 AntiXray v1.2.3 中
```

**Comment by wode490390** [comment]
PowerNukkit is not supported
